openapi: 3.0.3
info:
  title: University Management System API
  version: 1.0.0
  description: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3MzYzNzc2LCJpYXQiOjE3ODY0NjM3NzYsImp0aSI6ImQzZjYyNGRmZDg5OTRjYWU5NTdkM2Q5MjAxMGViNzc2IiwidXNlcl9pZCI6IjEifQ.zOID6ffGWDV1eztkhZlE5yhJPD4svHcm2kSqtWm3t4g
paths:
  /api/student/register/:
    post:
      operationId: student_register_create
      summary: Student Registraion
      tags:
      - Student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentRegisterRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StudentRegisterRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StudentRegisterRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentRegister'
          description: ''
  /api/verify-email-link/{uid}/{token}/:
    post:
      operationId: verify_email_link_create
      summary: Verify Email with link
      parameters:
      - in: path
        name: token
        schema:
          type: string
        required: true
      - in: path
        name: uid
        schema:
          type: string
        required: true
      tags:
      - Student
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/verify-email-otp/:
    post:
      operationId: verify_email_otp_create
      summary: Verify Email with otp
      tags:
      - Student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailByOTPRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyEmailByOTPRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VerifyEmailByOTPRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyEmailByOTP'
          description: ''
  /api/resend-verification-email/:
    post:
      operationId: resend_verification_email_create
      summary: Resend verification Link and Otp
      tags:
      - Student
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/student/:
    get:
      operationId: student_list
      summary: All Student Info
      parameters:
      - in: query
        name: approval_status
        schema:
          type: string
          enum:
          - approved
          - pending
          - rejected
        description: |-
          * `pending` - Pending
          * `approved` - Approved
          * `rejected` - Rejected
      - in: query
        name: department
        schema:
          type: integer
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - Student
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
          description: ''
  /api/student/{id}/:
    get:
      operationId: student_retrieve
      summary: Student Info - Admin Only
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Student
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    put:
      operationId: student_update
      summary: Student Info - Admin Only
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StudentRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StudentRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    patch:
      operationId: student_partial_update
      summary: Student Info - Admin Only
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStudentRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStudentRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStudentRequest'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
    delete:
      operationId: student_destroy
      summary: Student Info - Admin Only
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Student
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/student/{id}/generate-student-id/:
    post:
      operationId: student_generate_student_id_create
      summary: Generate Student Id
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Student
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/student/{id}/approve/:
    post:
      operationId: student_approve_create
      summary: Approve Student
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Student
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/student/{id}/reject/:
    post:
      operationId: student_reject_create
      summary: Reject Student
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Student
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    ApprovalStatusEnum:
      enum:
      - pending
      - approved
      - rejected
      type: string
      description: |-
        * `pending` - Pending
        * `approved` - Approved
        * `rejected` - Rejected
    PatchedStudentRequest:
      type: object
      properties:
        user:
          type: integer
        department:
          type: integer
          nullable: true
        student_id:
          type: string
          nullable: true
          maxLength: 50
        session:
          type: integer
          nullable: true
        year_semester:
          type: integer
          nullable: true
        cgpa:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        phone:
          type: string
          nullable: true
          maxLength: 20
        father_name:
          type: string
          nullable: true
          maxLength: 255
        father_phone:
          type: string
          nullable: true
          maxLength: 20
        mother_name:
          type: string
          nullable: true
          maxLength: 255
        mother_phone:
          type: string
          nullable: true
          maxLength: 20
        approval_status:
          $ref: '#/components/schemas/ApprovalStatusEnum'
        address:
          type: string
          nullable: true
    Student:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
        name:
          type: string
          readOnly: true
        email:
          type: string
          format: email
          readOnly: true
        department:
          type: integer
          nullable: true
        department_name:
          type: string
          readOnly: true
        student_id:
          type: string
          nullable: true
          maxLength: 50
        session:
          type: integer
          nullable: true
        year_semester:
          type: integer
          nullable: true
        year:
          type: string
          readOnly: true
        semester:
          type: string
          readOnly: true
        cgpa:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        phone:
          type: string
          nullable: true
          maxLength: 20
        father_name:
          type: string
          nullable: true
          maxLength: 255
        father_phone:
          type: string
          nullable: true
          maxLength: 20
        mother_name:
          type: string
          nullable: true
          maxLength: 255
        mother_phone:
          type: string
          nullable: true
          maxLength: 20
        approval_status:
          $ref: '#/components/schemas/ApprovalStatusEnum'
        address:
          type: string
          nullable: true
        image:
          type: string
          format: uri
          nullable: true
          readOnly: true
      required:
      - department_name
      - email
      - id
      - image
      - name
      - semester
      - user
      - year
    StudentRegister:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        email:
          type: string
          format: email
        department:
          type: integer
        session:
          type: integer
      required:
      - department
      - email
      - name
      - session
    StudentRegisterRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
        confirm_password:
          type: string
          writeOnly: true
          minLength: 1
        department:
          type: integer
        session:
          type: integer
      required:
      - confirm_password
      - department
      - email
      - name
      - password
      - session
    StudentRequest:
      type: object
      properties:
        user:
          type: integer
        department:
          type: integer
          nullable: true
        student_id:
          type: string
          nullable: true
          maxLength: 50
        session:
          type: integer
          nullable: true
        year_semester:
          type: integer
          nullable: true
        cgpa:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        phone:
          type: string
          nullable: true
          maxLength: 20
        father_name:
          type: string
          nullable: true
          maxLength: 255
        father_phone:
          type: string
          nullable: true
          maxLength: 20
        mother_name:
          type: string
          nullable: true
          maxLength: 255
        mother_phone:
          type: string
          nullable: true
          maxLength: 20
        approval_status:
          $ref: '#/components/schemas/ApprovalStatusEnum'
        address:
          type: string
          nullable: true
      required:
      - user
    VerifyEmailByOTP:
      type: object
      properties:
        email:
          type: string
          format: email
        otp:
          type: string
          maxLength: 6
          minLength: 6
      required:
      - email
      - otp
    VerifyEmailByOTPRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        otp:
          type: string
          minLength: 6
          maxLength: 6
      required:
      - email
      - otp
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
