# Generated by Django 6.0.7 on 2026-07-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='father',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother',
            new_name='mother_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinvitation',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invitations', to='Management.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherinvitation',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
