# Generated by Django 6.0.7 on 2026-07-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_rename_father_student_father_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='credit',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('viva', 'Viva'), ('project', 'Project')], default='theory', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
        migrations.CreateModel(
            name='CourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculation_type', models.CharField(choices=[('individual', 'Individual'), ('average', 'Average')], default='individual', max_length=20)),
                ('group', models.CharField(choices=[('none', 'No Group'), ('incourse', 'Incourse'), ('evaluation', 'Evaluation'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('presentation', 'Presentation'), ('viva', 'Viva')], default='none', max_length=30)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='Management.course')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
