# Generated by Django 6.0.7 on 2026-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_studentcourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsemesterresult',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
