# Generated by Django 6.0.7 on 2026-07-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_faculty_department_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-session_no'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='batch',
            new_name='session_no',
        ),
        migrations.RemoveField(
            model_name='examcommittee',
            name='chairman',
        ),
        migrations.AddField(
            model_name='examcommitteemember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examcommitteemember',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('member', 'Member'), ('tabulator', 'Tabulator'), ('external', 'External')], db_index=True, default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='examcommitteemember',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_committee_memberships', to='Management.teacher'),
        ),
    ]
