# Generated by Django 6.0.7 on 2026-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_studentsemesterresult_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Withdrawn'), ('incomplete', 'Incomplete'), ('failed', 'Failed'), ('retaken', 'Retaken')], default='enrolled', max_length=20),
        ),
    ]
