# Generated by Django 6.0.7 on 2026-07-18 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_course_options_rename_credits_course_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_course_code_per_department'),
        ),
        migrations.AddField(
            model_name='sessioncourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_courses', to='Management.course'),
        ),
        migrations.AddField(
            model_name='sessioncourse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_courses', to='Management.session'),
        ),
        migrations.AddField(
            model_name='sessioncourseteacher',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessioncourseteacher',
            name='session_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='Management.sessioncourse'),
        ),
        migrations.AddField(
            model_name='sessioncourseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='Management.teacher'),
        ),
        migrations.AddConstraint(
            model_name='sessioncourse',
            constraint=models.UniqueConstraint(fields=('session', 'course'), name='unique_session_course'),
        ),
        migrations.AddConstraint(
            model_name='sessioncourseteacher',
            constraint=models.UniqueConstraint(fields=('session_course', 'teacher'), name='unique_teacher_assignment'),
        ),
    ]
