# Generated by Django 6.0.7 on 2026-07-15 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_alter_session_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('assistant_professor', 'Assistant Professor'), ('associate_teacher', 'Assistant Teacher'), ('lecturer', 'Lecturer')], max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_invitations', to='Management.department')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Invitation',
                'verbose_name_plural': 'Teacher Invitations',
            },
        ),
    ]
