# Generated by Django 6.0.7 on 2026-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_teacherinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinvitation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teacherinvitation',
            name='employee_id',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
