# Generated by Django 6.0.7 on 2026-07-18 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_remove_student_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncourseteacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessioncourseteacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('failed', 'Failed')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='Management.sessioncourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='Management.student')),
            ],
            options={
                'ordering': ['student', 'session_course'],
                'constraints': [models.UniqueConstraint(fields=('student', 'session_course'), name='unique_student_session_course')],
            },
        ),
    ]
