# Generated by Django 6.0.7 on 2026-07-19 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_remove_courseassessment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassessment',
            name='group',
            field=models.CharField(choices=[('none', 'No Group'), ('incourse', 'Incourse'), ('evaluation', 'Evaluation'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('presentation', 'Presentation'), ('viva', 'Viva'), ('attendance', 'Attendance')], default='none', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentAssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='Management.courseassessment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_student_marks', to=settings.AUTH_USER_MODEL)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_marks', to='Management.studentcourse')),
            ],
            options={
                'ordering': ['student_course', 'assessment__display_order'],
                'constraints': [models.UniqueConstraint(fields=('student_course', 'assessment'), name='unique_student_assessment_mark')],
            },
        ),
    ]
