# Generated by Django 6.0.7 on 2026-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_attendancesession_studentattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassessment',
            name='is_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseassessment',
            name='group',
            field=models.CharField(choices=[('none', 'No Group'), ('incourse', 'Incourse'), ('evaluation', 'Evaluation'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('presentation', 'Presentation'), ('viva', 'Viva')], default='none', max_length=30),
        ),
    ]
