# Generated by Django 6.0.7 on 2026-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_remove_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncourseteacher',
            name='type',
            field=models.CharField(choices=[('course_teacher', 'Course Teacher'), ('external_teacher', 'External Teacher')], default='course_teacher', max_length=20),
        ),
    ]
