# Generated by Django 6.0.7 on 2026-09-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_sessioncourseteacher_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentassessmentmark',
            name='unique_student_assessment_mark',
        ),
        migrations.AddField(
            model_name='sessioncourseteacher',
            name='result_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentassessmentmark',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entered_marks', to='Management.teacher'),
        ),
        migrations.AddConstraint(
            model_name='studentassessmentmark',
            constraint=models.UniqueConstraint(fields=('student_course', 'assessment', 'teacher'), name='unique_student_assessment_mark_per_teacher'),
        ),
    ]
