# Generated by Django 6.0.7 on 2026-07-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_remove_courseassessment_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='Management.sessioncourse')),
            ],
        ),
    ]
