# Generated by Django 6.0.7 on 2026-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_sessioncourseresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncourse',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.DeleteModel(
            name='SessionCourseResult',
        ),
    ]
