# Generated by Django 6.0.7 on 2026-09-27 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_backfill_mark_teacher'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('email_change', 'Email Change'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('student_application', 'Student Application'), ('attendance_pending', 'Attendance Pending'), ('course_enrollment', 'Course Enrollment'), ('marks_published', 'Marks Published'), ('assignment_submitted', 'Assignment Submitted'), ('result_published', 'Result Published'), ('course_content_added', 'Course Content Added'), ('announcement', 'Announcement'), ('newsfeed_like', 'Newsfeed Like'), ('newsfeed_comment', 'Newsfeed Comment'), ('newsfeed_share', 'Newsfeed Share'), ('system', 'System'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('like', 'Like'), ('share', 'Share'), ('enrollment', 'Course Enrollment'), ('submission', 'Assignment Submission'), ('result', 'Result Published'), ('announcement', 'Announcement'), ('attendance', 'Attendance')], default='post', max_length=50)),
                ('content', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsfeed_items', to='contenttypes.contenttype')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_newsfeed_posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='Management.newsfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsfeed_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsfeedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='newsfeed/media/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='newsfeed/thumbnails/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsfeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Management.newsfeed')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newsfeed',
            index=models.Index(fields=['user', 'created_at'], name='Management__user_id_9b039f_idx'),
        ),
        migrations.AddIndex(
            model_name='newsfeed',
            index=models.Index(fields=['activity_type', 'created_at'], name='Management__activit_71aebb_idx'),
        ),
        migrations.AddIndex(
            model_name='newsfeed',
            index=models.Index(fields=['parent', 'created_at'], name='Management__parent__8900b9_idx'),
        ),
    ]
