# Generated by Django 6.0.7 on 2026-09-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_alter_notification_notification_type_newsfeed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='is_published',
        ),
    ]
