# Generated by Django 6.0.7 on 2026-07-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_alter_department_faculty_coursematerial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='is_visible',
        ),
    ]
