# Generated by Django 6.0.7 on 2026-10-03 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_remove_newsfeed_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('email_change', 'Email Change'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('student_application', 'Student Application'), ('attendance_pending', 'Attendance Pending'), ('course_enrollment', 'Course Enrollment'), ('marks_published', 'Marks Published'), ('assignment_submitted', 'Assignment Submitted'), ('result_published', 'Result Published'), ('course_content_added', 'Course Content Added'), ('announcement', 'Announcement'), ('complaint', 'Complaint'), ('newsfeed_like', 'Newsfeed Like'), ('newsfeed_comment', 'Newsfeed Comment'), ('newsfeed_share', 'Newsfeed Share'), ('system', 'System'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='ComplainBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('complain_to', models.CharField(choices=[('dept_chairman', 'Department Chairman'), ('dept_teacher', 'Department Teacher'), ('dept_all', 'Department All (Student + Teacher)'), ('all', 'All (All Dept Teacher + Student)')], default='dept_chairman', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='Management.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplainBoxMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complainbox/media/%Y/%m/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complainbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Management.complainbox')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complainbox',
            index=models.Index(fields=['user', 'created_at'], name='Management__user_id_a4232d_idx'),
        ),
        migrations.AddIndex(
            model_name='complainbox',
            index=models.Index(fields=['complain_to'], name='Management__complai_713400_idx'),
        ),
    ]
