# Generated by Django 6.0.7 on 2026-10-06 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_alter_notification_notification_type_complainbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('is_done', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time', 'created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='Management__user_id_370973_idx'), models.Index(fields=['user', 'is_done'], name='Management__user_id_a752ef_idx')],
            },
        ),
    ]
