# Generated by Django 6.0.7 on 2026-07-27 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_assignment_assignmentfile_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
