# Generated by Django 6.0.7 on 2026-08-23 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0019_sessioncourse_published_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('email_change', 'Email Change'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('student_application', 'Student Application'), ('attendance_pending', 'Attendance Pending'), ('course_enrollment', 'Course Enrollment'), ('marks_published', 'Marks Published'), ('assignment_submitted', 'Assignment Submitted'), ('result_published', 'Result Published'), ('announcement', 'Announcement'), ('system', 'System'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='Management__user_id_4ccba0_idx'), models.Index(fields=['user', 'created_at'], name='Management__user_id_d76249_idx')],
            },
        ),
    ]
