# Generated by Django 6.0.7 on 2026-08-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('email_change', 'Email Change'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('student_application', 'Student Application'), ('attendance_pending', 'Attendance Pending'), ('course_enrollment', 'Course Enrollment'), ('marks_published', 'Marks Published'), ('assignment_submitted', 'Assignment Submitted'), ('result_published', 'Result Published'), ('course_content_added', 'Course Content Added'), ('announcement', 'Announcement'), ('system', 'System'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
