# Generated by Django 6.0.7 on 2026-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0021_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('professor', 'Professor'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('lecturer', 'Lecturer')], default='lecturer', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinvitation',
            name='designation',
            field=models.CharField(choices=[('professor', 'Professor'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('lecturer', 'Lecturer')], max_length=50),
        ),
    ]
