from .student_serializers import StudentRegisterSerializer, VerifyEmailByOTPSerializer, ResendVerificationEmailSerializer, StudentSerializer
from .teacher_serializers import TeacherInvitationSerializer, TeacherRegisterSerializer, TeacherSerializer
from .auth_serializers import LoginSerializer, ChangePasswordSerializer, ForgotPasswordSerializer, ResetPasswordSerializer, ChangeEmailSerializer, VerifyChangeEmailSerializer
from .master_data_serializers import FacultySerializer, DepartmentSerializer, SessionSerializer, YearSemesterSerializer
from .profile_serializers import ProfileSerializer, UpdateStudentProfileSerializer, UpdateTeacherProfileSerializer
from .course_serializers import CourseSerializer, CourseAssessmentSerializer, SessionCourseSerializer, SessionCourseTeacherSerializer, StudentCourseSerializer
from .marks_attendance_serializers import StudentMarkSerializer, StudentAssessmentBulkSerializer, AssessmentStudentSerializer, AttendanceSessionSerializer, StudentAttendanceSerializer, AttendanceBulkSerializer, AttendanceStudentSerializer
from .result_serializers import StudentResultSerializer, SessionCourseResultSerializer
from .course_content_serializers import CourseMaterialSerializer, CourseMaterialFileSerializer, CourseMaterialCreateSerializer, CourseAnnouncementSerializer, CourseAnnouncementFileSerializer, CourseAnnouncementCreateSerializer, AssignmentSerializer, AssignmentFileSerializer, AssignmentCreateSerializer, AssignmentSubmissionSerializer, AssignmentSubmissionFileSerializer, AssignmentSubmissionCreateSerializer