from .auth_views import LoginView, RefreshTokenView, ChangePasswordView, ForgotPasswordView, ResetPasswordView, ChangeEmailView, VerifyChangeEmailView
from .student_views import StudentRegisterView, VerifyEmailByLinkView, VerifyEmailByOTPView, ResendVerificationEmailView, StudentListView, StudentDetailView, StudentApproveView, StudentRejectView
from .teacher_views import TeacherInvitationView, TeacherRegisterView, TeacherListView, TeacherDetailView
from .master_data_views import FacultyViewSet, DepartmentViewSet, SessionViewSet, YearSemesterViewSet
from .profile_views import ProfileView
from .course_views import CourseViewSet, CourseAssessmentViewSet, SessionCourseViewSet, SessionCourseTeacherViewSet, StudentCourseListView, StudentCourseDetailView
from .marks_attendance_views import AssessmentMarksView, AttendanceSessionView, AttendanceRecordView
from .result_views import StudentResultAPIView, SessionCourseResultAPIView
from .course_content_views import CourseMaterialViewSet, CourseAnnouncementViewSet, AssignmentViewSet, AssignmentSubmissionViewSet